// src/renderer/src/components/Versions.tsx
import type { Component } from 'solid-js'

import { createSignal } from 'solid-js'

const Versions: Component = () => {
  const [versions] = createSignal(window.electron.process.versions)

  return (
    <ul class="versions">
      <li class="electron-version">
        Electron v
        {versions().electron}
      </li>
      <li class="chrome-version">
        Chromium v
        {versions().chrome}
      </li>
      <li class="node-version">
        Node v
        {versions().node}
      </li>
    </ul>
  )
}

export default Versions

// src/renderer/src/components/Versions.vue
<script setup lang="ts">
import { reactive } from "vue";

const versions = reactive({ ...window.api.process.versions });
</script>

<template>
  <ul class="versions">
    <li class="electron-version">
      Electron v{{ versions.electron }}
    </li>
    <li class="chrome-version">
      Chromium v{{ versions.chrome }}
    </li>
    <li class="node-version">
      Node v{{ versions.node }}
    </li>
  </ul>
</template>
